services:
  node-api:
    container_name: node-api
    image: node-api:dev
    build:
      context: .
      target: development
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 4444:4444
    command: npm run start:dev
    environment:
      NODE_ENV: development
      SERVER_PORT: 4444
      DB_DATABASE: node_api
      DB_CONNECTION_STRING: mysql://nodeapi_root:j5m966qp7jiypfda@node-api-mysql:3306
    networks:
      - node-api-connect

  node-api-mysql:
    container_name: node-api-mysql
    image: mysql
    environment:
      MYSQL_USER: nodeapi_root
      MYSQL_PASSWORD: j5m966qp7jiypfda
      MYSQL_ROOT_PASSWORD: m45ug42qkr5pdzbb
      MYSQL_DATABASE: node_api
    ports:
      - 3308:3306
    volumes:
      - ~/docker/volumes/NodeApi_MySQL:/var/lib/mysql
    networks:
      - node-api-connect
    logging:
      driver: none

networks:
  node-api-connect:
    driver: bridge
    name: node-api-connect
